### ISSUE TITLE
Issue auth token

### ISSUE THREAD

**Issue by bmulholland** [trycourier/courier-ruby#30]
## Expected Behavior

https://www.courier.com/docs/platform/inbox/authentication/ says HMAC is deprecated, and to use the API to create a JWS access toked. But this gem doesn't seem to support that.

## Actual Behavior

I'll use HMAC for now.

**Comment by tk26** [comment]
hey @bmulholland - I've a PR to add support for the API. should be live soon!

**Comment by tk26** [comment]
circling back: @bmulholland the API is live and should be available in v1.10.0

**Comment by niam0r** [comment]
Hi, I'm trying to understand if it's now possible to use the Courier client to generate the auth token for a user as in [this](https://www.courier.com/docs/reference/auth/issue-token/)

Is there a way to something along the line of:
```
courier_client.auth_token(user_id: "my_user_id", expires_in: 1.day)
```

Thanks

**Comment by tk26** [comment]
@niam0r try `client.auth_tokens.issue_token(scope: "user_id:user_id_you_want_to_create_scope_for read:messages")`

**Comment by tk26** [comment]
Closing this issue as this has been fixed in the release. if you run into any issues feel free to open new one or reach Courier support!
